'use client';
import {useEffect,useRef,useState} from 'react';
const DEFAULT='SPY,QQQ,NVDA,TSLA,AAPL,META,BAC,PLTR,AMZN';
function cardText(a){return `${a.symbol} ${a.signal}\nPrecio: ${a.close}\nEntrada CALL arriba de: ${a.levels?.entryCall}\nEntrada PUT abajo de: ${a.levels?.entryPut}\nStop CALL: ${a.levels?.stopCall} | Stop PUT: ${a.levels?.stopPut}\nTarget CALL: ${a.levels?.targetCall} | Target PUT: ${a.levels?.targetPut}\nRSI: ${a.indicators?.rsi} | MACD hist: ${a.indicators?.macdHist}\nStrike sugerido: ${a.optionIdea?.strike||'N/A'} ${a.optionIdea?.type||''}\nExp: ${a.optionIdea?.expiration}\nRiesgo: ${a.optionIdea?.maxPremiumRisk}`}
export default function Page(){
 const [ticker,setTicker]=useState(''),[watch,setWatch]=useState(DEFAULT),[loading,setLoading]=useState(false),[analysis,setAnalysis]=useState(null),[scan,setScan]=useState(null),[chat,setChat]=useState([]),bottom=useRef(null);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[chat,analysis,scan,loading]);
 async function analyze(sym){sym=(sym||ticker).trim().toUpperCase(); if(!sym||loading)return; setLoading(true); setTicker(''); setScan(null); try{const r=await fetch('/api/analyze?symbol='+sym); const d=await r.json(); if(!r.ok)throw new Error(d.error); setAnalysis(d.analysis); setChat(p=>[...p,{role:'assistant',text:`✅ Análisis listo para ${sym}. Señal: ${d.analysis.signal}`}]);}catch(e){setChat(p=>[...p,{role:'assistant',text:'❌ '+e.message+'\nRevisa API key o límite de datos.'}])} finally{setLoading(false)}}
 async function scanner(){setLoading(true);setAnalysis(null);try{const r=await fetch('/api/scan?symbols='+encodeURIComponent(watch));const d=await r.json();if(!r.ok)throw new Error(d.error);setScan(d);setChat(p=>[...p,{role:'assistant',text:`🏆 Mejor activo del scanner: ${d.best?.symbol||'N/A'} — ${d.best?.signal||''}`}]);}catch(e){setChat(p=>[...p,{role:'assistant',text:'❌ '+e.message}])}finally{setLoading(false)}}
 async function alertWhatsApp(){const a=analysis||scan?.best;if(!a)return;const r=await fetch('/api/alert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'ALERTA TRADING IA\n'+cardText(a)+'\n⚠️ Educativo, no consejo financiero.'})});const d=await r.json();setChat(p=>[...p,{role:'assistant',text:d.ok?'📲 Alerta enviada por WhatsApp.':'⚠️ WhatsApp no configurado todavía: '+d.error}])}
 function Box({children}){return <div style={{background:'rgba(0,35,18,.85)',border:'1px solid #17452b',borderRadius:12,padding:14,margin:'12px 0',lineHeight:1.55}}>{children}</div>}
 function Analysis({a}){return <Box><h2 style={{color:'#00ff50'}}>{a.symbol} — {a.signal}</h2><p><b>Precio:</b> {a.close} | <b>Puntaje:</b> {a.score}</p><p><b>Entrada CALL:</b> arriba de {a.levels.entryCall} | <b>Entrada PUT:</b> abajo de {a.levels.entryPut}</p><p><b>Stop CALL:</b> {a.levels.stopCall} | <b>Stop PUT:</b> {a.levels.stopPut}</p><p><b>Target CALL:</b> {a.levels.targetCall} | <b>Target PUT:</b> {a.levels.targetPut}</p><p><b>Soporte:</b> {a.levels.support} | <b>Resistencia:</b> {a.levels.resistance}</p><p><b>RSI:</b> {a.indicators.rsi} | <b>EMA20:</b> {a.indicators.ema20} | <b>EMA50:</b> {a.indicators.ema50} | <b>MACD:</b> {a.indicators.macdHist}</p><p><b>Opción:</b> {a.optionIdea.type} {a.optionIdea.strike||''} | <b>Exp:</b> {a.optionIdea.expiration}</p><p><b>Riesgo:</b> {a.optionIdea.maxPremiumRisk}</p><p><b>Razones:</b> {a.reasons.join(' · ')}</p><button onClick={alertWhatsApp} style={btn}>MANDAR ALERTA WHATSAPP</button><p style={{color:'#75aa83',fontSize:12}}>⚠️ Educativo — confirma en Webull/TradingView antes de entrar.</p></Box>}
 const btn={background:'#00ff50',color:'#001000',border:0,borderRadius:8,padding:'10px 14px',fontWeight:800,marginTop:8};
 return <main style={{fontFamily:'monospace',background:'#050d14',minHeight:'100vh',color:'#c8ffd4'}}><style>{`*{box-sizing:border-box}input,textarea,button{font-family:monospace}.grid{background-image:linear-gradient(rgba(0,255,80,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(0,255,80,.05) 1px,transparent 1px);background-size:40px 40px}`}</style><div className='grid' style={{minHeight:'100vh',padding:18}}><div style={{maxWidth:960,margin:'0 auto'}}><header style={{borderBottom:'1px solid #17452b',paddingBottom:12}}><h1 style={{color:'#00ff50',letterSpacing:2}}>TRADING.AI // OPTIONS DESK</h1><p>Scanner + entradas/salidas + ranking + alertas WhatsApp opcionales</p></header><Box><h3>1) Analizar un solo ticker</h3><div style={{display:'flex',gap:8}}><input value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} onKeyDown={e=>{if(e.key==='Enter')analyze()}} placeholder='Ej: NVDA, TSLA, SPY...' style={inp}/><button onClick={()=>analyze()} style={btn}>ANALIZAR</button></div></Box><Box><h3>2) Scanner: decide cuál activo está mejor</h3><textarea value={watch} onChange={e=>setWatch(e.target.value.toUpperCase())} style={{...inp,width:'100%',minHeight:58}}/><button onClick={scanner} style={btn}>ESCANEAR Y RANKEAR</button></Box>{loading&&<p style={{color:'#00ff50'}}>Analizando...</p>}{analysis&&<Analysis a={analysis}/>} {scan&&<Box><h2>Ranking de mejores setups</h2>{scan.results.map((r,i)=>r.error?<p key={r.symbol}>{r.symbol}: sin datos</p>:<div key={r.symbol} style={{borderTop:'1px solid #17452b',padding:'10px 0'}}><b>{i+1}. {r.symbol}</b> — {r.signal} — score {r.score}<br/>Entrada: CALL &gt; {r.levels.entryCall} / PUT &lt; {r.levels.entryPut}<br/>Stop: CALL {r.levels.stopCall} / PUT {r.levels.stopPut}<br/>RSI {r.indicators.rsi} · MACD {r.indicators.macdHist}</div>)}<button onClick={alertWhatsApp} style={btn}>MANDAR MEJOR SETUP A WHATSAPP</button></Box>}{chat.slice(-3).map((m,i)=><Box key={i}>{m.text}</Box>)}<div ref={bottom}/><p style={{textAlign:'center',color:'#5f9970',fontSize:12}}>⚠️ Solo educativo. No compra ni vende automáticamente.</p></div></div></main>}
const inp={flex:1,background:'#061109',border:'1px solid #17452b',borderRadius:8,color:'#c8ffd4',padding:12,fontSize:15};
